<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <RootNamespace>CasCap.Common.AI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CasCap.Common.AI\CasCap.Common.AI.csproj" />
    <ProjectReference Include="..\CasCap.Common.Testing\CasCap.Common.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
