global using CasCap.Common.Extensions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Collections.Specialized;
global using System.Net;
global using System.Net.Http.Headers;
global using Xunit;
global using Xunit.Abstractions;
