global using CasCap.Common.Abstractions;
global using CasCap.Common.Extensions;
global using CasCap.Common.Models;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Xunit;
