global using CasCap.Abstractions;
global using CasCap.Common.Extensions;
global using CasCap.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.Threading.Tasks;
global using Xunit;
global using Xunit.Abstractions;
