parameters:
- name: BuildConfiguration
  displayName: Select BuildConfiguration
  type: string
  default: release
  values:
  - release
  - debug

trigger:
  batch: true
  branches:
    include:
    - main
    - hotfix/*
    - feature/*
  paths:
    exclude:
    - .github
    - LICENSE
    - README.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: f2calv/CasCap.YAMLTemplates
    endpoint: github.com_f2calv
    ref: refs/heads/main
  containers:
  - container: redis
    image: redis
    ports:
    - 6379:6379

variables:
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - group: nuget-prod
- ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - group: nuget-dev

pool:
  vmImage: ubuntu-latest

services:
  redis: redis

#can't see to use services w/extends - needs more investigation...
#extends:
#  template: pipelines/dotnet-publish-nuget-v1.yml@sharedTemplates
steps:
- template: pipelines/dotnet-publish-nuget-v1.yml@sharedTemplates
  parameters:
    BuildConfiguration: ${{ parameters.BuildConfiguration }}
    CoverageInclude: '[CasCap.*]*'
    gitHubConnection: github.com_f2calv
    # services:
    #   redis: redis