name: .NET

on:
  #workflow_dispatch: this only works when in default branch?
  push:
    branches: [ main, 'feature/*' ]
    # paths-ignore:
    #   - ".azure-pipelines/**"
    #   #- '.github/**'
    #   - LICENSE
    #   - README.md
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    - run: |
        dotnet tool update -g GitVersion.Tool
        $HOME/.dotnet/tools/dotnet-gitversion ${{ github.workspace }} /output buildserver /nofetch
      shell: bash
      #condition: eq(variables['Agent.OS'], 'Windows_NT')
      #displayName: GitVersion (Windows)
      continue-on-error: false

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: .NET Core 3.1.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: .NET 5.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
    - name: dotnet restore
      run: dotnet restore --verbosity minimal --configfile nuget.config

    - name: dotnet build
      run: dotnet build --no-restore --nologo

    - name: dotnet test
      run: dotnet test --no-build --verbosity normal

    - name: dotnet pack
      if: ${{ success() && !github.base_ref }}
      run: dotnet pack

    - name: dotnet push
      if: ${{ success() && !github.base_ref }}
      run: dotnet push
